steps:
  # build batch image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'batch'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/run/batch:latest', '.']

  # push（使用你已存在的 run 仓库，无需新建）
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'batch'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/run/batch:latest']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/run/batch:latest'

timeout: '600s'
